---
numberOfCPUThreads: 1
captureMethod: "XIMAGESRC"
serialPort: "GW_ESP8266_Acer"
baudRate: "500000"
defaultLedMatrix: "FullScreen"
autoDetectBlackBars: false
topLed: 32
leftLed: 18
rightLed: 18
bottomLeftLed: 12
bottomRightLed: 12
bottomRowLed: 26
orientation: "Anticlockwise"
timeout: 2000
screenResX: 1920
screenResY: 1080
osScaling: 100
gamma: 2.2
whiteTemperature: 1
mqttServer: "tcp://192.168.178.20:1883"
mqttTopic: "glowwormluciferin_acer"
mqttUsername: "patrick"
mqttPwd: "phfu064X"
mqttEnable: true
mqttStream: true
checkForUpdates: true
autoStartCapture: false
eyeCare: false
toggleLed: false
desiredFramerate: "30"
colorChooser: "255,0,0,255"
brightness: 255
ledStartOffset: 0
splitBottomRow: true
startWithSystem: false
multiMonitor: 2
monitorNumber: 1
syncCheck: true
ledMatrix:
  FullScreen:
    1:
      x: 1129
      "y": 972
      dimension: 58
    2:
      x: 1197
      "y": 972
      dimension: 58
    3:
      x: 1265
      "y": 972
      dimension: 58
    4:
      x: 1333
      "y": 972
      dimension: 58
    5:
      x: 1401
      "y": 972
      dimension: 58
    6:
      x: 1469
      "y": 972
      dimension: 58
    7:
      x: 1537
      "y": 972
      dimension: 58
    8:
      x: 1605
      "y": 972
      dimension: 58
    9:
      x: 1673
      "y": 972
      dimension: 58
    10:
      x: 1741
      "y": 972
      dimension: 58
    11:
      x: 1809
      "y": 972
      dimension: 58
    12:
      x: 1877
      "y": 972
      dimension: 58
    13:
      x: 1800
      "y": 924
      dimension: 38
    14:
      x: 1800
      "y": 876
      dimension: 38
    15:
      x: 1800
      "y": 828
      dimension: 38
    16:
      x: 1800
      "y": 780
      dimension: 38
    17:
      x: 1800
      "y": 732
      dimension: 38
    18:
      x: 1800
      "y": 684
      dimension: 38
    19:
      x: 1800
      "y": 636
      dimension: 38
    20:
      x: 1800
      "y": 588
      dimension: 38
    21:
      x: 1800
      "y": 540
      dimension: 38
    22:
      x: 1800
      "y": 492
      dimension: 38
    23:
      x: 1800
      "y": 444
      dimension: 38
    24:
      x: 1800
      "y": 396
      dimension: 38
    25:
      x: 1800
      "y": 348
      dimension: 38
    26:
      x: 1800
      "y": 300
      dimension: 38
    27:
      x: 1800
      "y": 252
      dimension: 38
    28:
      x: 1800
      "y": 204
      dimension: 38
    29:
      x: 1800
      "y": 156
      dimension: 38
    30:
      x: 1800
      "y": 108
      dimension: 38
    31:
      x: 1860
      "y": 8
      dimension: 50
    32:
      x: 1800
      "y": 8
      dimension: 50
    33:
      x: 1740
      "y": 8
      dimension: 50
    34:
      x: 1680
      "y": 8
      dimension: 50
    35:
      x: 1620
      "y": 8
      dimension: 50
    36:
      x: 1560
      "y": 8
      dimension: 50
    37:
      x: 1500
      "y": 8
      dimension: 50
    38:
      x: 1440
      "y": 8
      dimension: 50
    39:
      x: 1380
      "y": 8
      dimension: 50
    40:
      x: 1320
      "y": 8
      dimension: 50
    41:
      x: 1260
      "y": 8
      dimension: 50
    42:
      x: 1200
      "y": 8
      dimension: 50
    43:
      x: 1140
      "y": 8
      dimension: 50
    44:
      x: 1080
      "y": 8
      dimension: 50
    45:
      x: 1020
      "y": 8
      dimension: 50
    46:
      x: 960
      "y": 8
      dimension: 50
    47:
      x: 900
      "y": 8
      dimension: 50
    48:
      x: 840
      "y": 8
      dimension: 50
    49:
      x: 780
      "y": 8
      dimension: 50
    50:
      x: 720
      "y": 8
      dimension: 50
    51:
      x: 660
      "y": 8
      dimension: 50
    52:
      x: 600
      "y": 8
      dimension: 50
    53:
      x: 540
      "y": 8
      dimension: 50
    54:
      x: 480
      "y": 8
      dimension: 50
    55:
      x: 420
      "y": 8
      dimension: 50
    56:
      x: 360
      "y": 8
      dimension: 50
    57:
      x: 300
      "y": 8
      dimension: 50
    58:
      x: 240
      "y": 8
      dimension: 50
    59:
      x: 180
      "y": 8
      dimension: 50
    60:
      x: 120
      "y": 8
      dimension: 50
    61:
      x: 60
      "y": 8
      dimension: 50
    62:
      x: 0
      "y": 8
      dimension: 50
    63:
      x: 70
      "y": 108
      dimension: 38
    64:
      x: 70
      "y": 156
      dimension: 38
    65:
      x: 70
      "y": 204
      dimension: 38
    66:
      x: 70
      "y": 252
      dimension: 38
    67:
      x: 70
      "y": 300
      dimension: 38
    68:
      x: 70
      "y": 348
      dimension: 38
    69:
      x: 70
      "y": 396
      dimension: 38
    70:
      x: 70
      "y": 444
      dimension: 38
    71:
      x: 70
      "y": 492
      dimension: 38
    72:
      x: 70
      "y": 540
      dimension: 38
    73:
      x: 70
      "y": 588
      dimension: 38
    74:
      x: 70
      "y": 636
      dimension: 38
    75:
      x: 70
      "y": 684
      dimension: 38
    76:
      x: 70
      "y": 732
      dimension: 38
    77:
      x: 70
      "y": 780
      dimension: 38
    78:
      x: 70
      "y": 828
      dimension: 38
    79:
      x: 70
      "y": 876
      dimension: 38
    80:
      x: 70
      "y": 924
      dimension: 38
    81:
      x: 0
      "y": 972
      dimension: 58
    82:
      x: 68
      "y": 972
      dimension: 58
    83:
      x: 136
      "y": 972
      dimension: 58
    84:
      x: 204
      "y": 972
      dimension: 58
    85:
      x: 272
      "y": 972
      dimension: 58
    86:
      x: 340
      "y": 972
      dimension: 58
    87:
      x: 408
      "y": 972
      dimension: 58
    88:
      x: 476
      "y": 972
      dimension: 58
    89:
      x: 544
      "y": 972
      dimension: 58
    90:
      x: 612
      "y": 972
      dimension: 58
    91:
      x: 680
      "y": 972
      dimension: 58
    92:
      x: 748
      "y": 972
      dimension: 58
  Letterbox:
    1:
      x: 1129
      "y": 864
      dimension: 58
    2:
      x: 1197
      "y": 864
      dimension: 58
    3:
      x: 1265
      "y": 864
      dimension: 58
    4:
      x: 1333
      "y": 864
      dimension: 58
    5:
      x: 1401
      "y": 864
      dimension: 58
    6:
      x: 1469
      "y": 864
      dimension: 58
    7:
      x: 1537
      "y": 864
      dimension: 58
    8:
      x: 1605
      "y": 864
      dimension: 58
    9:
      x: 1673
      "y": 864
      dimension: 58
    10:
      x: 1741
      "y": 864
      dimension: 58
    11:
      x: 1809
      "y": 864
      dimension: 58
    12:
      x: 1877
      "y": 864
      dimension: 58
    13:
      x: 1800
      "y": 828
      dimension: 26
    14:
      x: 1800
      "y": 792
      dimension: 26
    15:
      x: 1800
      "y": 756
      dimension: 26
    16:
      x: 1800
      "y": 720
      dimension: 26
    17:
      x: 1800
      "y": 684
      dimension: 26
    18:
      x: 1800
      "y": 648
      dimension: 26
    19:
      x: 1800
      "y": 612
      dimension: 26
    20:
      x: 1800
      "y": 576
      dimension: 26
    21:
      x: 1800
      "y": 540
      dimension: 26
    22:
      x: 1800
      "y": 504
      dimension: 26
    23:
      x: 1800
      "y": 468
      dimension: 26
    24:
      x: 1800
      "y": 432
      dimension: 26
    25:
      x: 1800
      "y": 396
      dimension: 26
    26:
      x: 1800
      "y": 360
      dimension: 26
    27:
      x: 1800
      "y": 324
      dimension: 26
    28:
      x: 1800
      "y": 288
      dimension: 26
    29:
      x: 1800
      "y": 252
      dimension: 26
    30:
      x: 1800
      "y": 216
      dimension: 26
    31:
      x: 1860
      "y": 116
      dimension: 50
    32:
      x: 1800
      "y": 116
      dimension: 50
    33:
      x: 1740
      "y": 116
      dimension: 50
    34:
      x: 1680
      "y": 116
      dimension: 50
    35:
      x: 1620
      "y": 116
      dimension: 50
    36:
      x: 1560
      "y": 116
      dimension: 50
    37:
      x: 1500
      "y": 116
      dimension: 50
    38:
      x: 1440
      "y": 116
      dimension: 50
    39:
      x: 1380
      "y": 116
      dimension: 50
    40:
      x: 1320
      "y": 116
      dimension: 50
    41:
      x: 1260
      "y": 116
      dimension: 50
    42:
      x: 1200
      "y": 116
      dimension: 50
    43:
      x: 1140
      "y": 116
      dimension: 50
    44:
      x: 1080
      "y": 116
      dimension: 50
    45:
      x: 1020
      "y": 116
      dimension: 50
    46:
      x: 960
      "y": 116
      dimension: 50
    47:
      x: 900
      "y": 116
      dimension: 50
    48:
      x: 840
      "y": 116
      dimension: 50
    49:
      x: 780
      "y": 116
      dimension: 50
    50:
      x: 720
      "y": 116
      dimension: 50
    51:
      x: 660
      "y": 116
      dimension: 50
    52:
      x: 600
      "y": 116
      dimension: 50
    53:
      x: 540
      "y": 116
      dimension: 50
    54:
      x: 480
      "y": 116
      dimension: 50
    55:
      x: 420
      "y": 116
      dimension: 50
    56:
      x: 360
      "y": 116
      dimension: 50
    57:
      x: 300
      "y": 116
      dimension: 50
    58:
      x: 240
      "y": 116
      dimension: 50
    59:
      x: 180
      "y": 116
      dimension: 50
    60:
      x: 120
      "y": 116
      dimension: 50
    61:
      x: 60
      "y": 116
      dimension: 50
    62:
      x: 0
      "y": 116
      dimension: 50
    63:
      x: 70
      "y": 216
      dimension: 26
    64:
      x: 70
      "y": 252
      dimension: 26
    65:
      x: 70
      "y": 288
      dimension: 26
    66:
      x: 70
      "y": 324
      dimension: 26
    67:
      x: 70
      "y": 360
      dimension: 26
    68:
      x: 70
      "y": 396
      dimension: 26
    69:
      x: 70
      "y": 432
      dimension: 26
    70:
      x: 70
      "y": 468
      dimension: 26
    71:
      x: 70
      "y": 504
      dimension: 26
    72:
      x: 70
      "y": 540
      dimension: 26
    73:
      x: 70
      "y": 576
      dimension: 26
    74:
      x: 70
      "y": 612
      dimension: 26
    75:
      x: 70
      "y": 648
      dimension: 26
    76:
      x: 70
      "y": 684
      dimension: 26
    77:
      x: 70
      "y": 720
      dimension: 26
    78:
      x: 70
      "y": 756
      dimension: 26
    79:
      x: 70
      "y": 792
      dimension: 26
    80:
      x: 70
      "y": 828
      dimension: 26
    81:
      x: 0
      "y": 864
      dimension: 58
    82:
      x: 68
      "y": 864
      dimension: 58
    83:
      x: 136
      "y": 864
      dimension: 58
    84:
      x: 204
      "y": 864
      dimension: 58
    85:
      x: 272
      "y": 864
      dimension: 58
    86:
      x: 340
      "y": 864
      dimension: 58
    87:
      x: 408
      "y": 864
      dimension: 58
    88:
      x: 476
      "y": 864
      dimension: 58
    89:
      x: 544
      "y": 864
      dimension: 58
    90:
      x: 612
      "y": 864
      dimension: 58
    91:
      x: 680
      "y": 864
      dimension: 58
    92:
      x: 748
      "y": 864
      dimension: 58
  Pillarbox:
    1:
      x: 1085
      "y": 918
      dimension: 37
    2:
      x: 1131
      "y": 918
      dimension: 37
    3:
      x: 1179
      "y": 918
      dimension: 37
    4:
      x: 1226
      "y": 918
      dimension: 37
    5:
      x: 1274
      "y": 918
      dimension: 37
    6:
      x: 1321
      "y": 918
      dimension: 37
    7:
      x: 1369
      "y": 918
      dimension: 37
    8:
      x: 1416
      "y": 918
      dimension: 37
    9:
      x: 1464
      "y": 918
      dimension: 37
    10:
      x: 1511
      "y": 918
      dimension: 37
    11:
      x: 1559
      "y": 918
      dimension: 37
    12:
      x: 1606
      "y": 918
      dimension: 37
    13:
      x: 1510
      "y": 876
      dimension: 32
    14:
      x: 1510
      "y": 834
      dimension: 32
    15:
      x: 1510
      "y": 792
      dimension: 32
    16:
      x: 1510
      "y": 750
      dimension: 32
    17:
      x: 1510
      "y": 708
      dimension: 32
    18:
      x: 1510
      "y": 666
      dimension: 32
    19:
      x: 1510
      "y": 624
      dimension: 32
    20:
      x: 1510
      "y": 582
      dimension: 32
    21:
      x: 1510
      "y": 540
      dimension: 32
    22:
      x: 1510
      "y": 498
      dimension: 32
    23:
      x: 1510
      "y": 456
      dimension: 32
    24:
      x: 1510
      "y": 414
      dimension: 32
    25:
      x: 1510
      "y": 372
      dimension: 32
    26:
      x: 1510
      "y": 330
      dimension: 32
    27:
      x: 1510
      "y": 288
      dimension: 32
    28:
      x: 1510
      "y": 246
      dimension: 32
    29:
      x: 1510
      "y": 204
      dimension: 32
    30:
      x: 1510
      "y": 162
      dimension: 32
    31:
      x: 1589
      "y": 62
      dimension: 31
    32:
      x: 1548
      "y": 62
      dimension: 31
    33:
      x: 1507
      "y": 62
      dimension: 31
    34:
      x: 1466
      "y": 62
      dimension: 31
    35:
      x: 1425
      "y": 62
      dimension: 31
    36:
      x: 1384
      "y": 62
      dimension: 31
    37:
      x: 1343
      "y": 62
      dimension: 31
    38:
      x: 1302
      "y": 62
      dimension: 31
    39:
      x: 1261
      "y": 62
      dimension: 31
    40:
      x: 1220
      "y": 62
      dimension: 31
    41:
      x: 1179
      "y": 62
      dimension: 31
    42:
      x: 1138
      "y": 62
      dimension: 31
    43:
      x: 1097
      "y": 62
      dimension: 31
    44:
      x: 1056
      "y": 62
      dimension: 31
    45:
      x: 1015
      "y": 62
      dimension: 31
    46:
      x: 974
      "y": 62
      dimension: 31
    47:
      x: 933
      "y": 62
      dimension: 31
    48:
      x: 892
      "y": 62
      dimension: 31
    49:
      x: 851
      "y": 62
      dimension: 31
    50:
      x: 810
      "y": 62
      dimension: 31
    51:
      x: 769
      "y": 62
      dimension: 31
    52:
      x: 728
      "y": 62
      dimension: 31
    53:
      x: 687
      "y": 62
      dimension: 31
    54:
      x: 646
      "y": 62
      dimension: 31
    55:
      x: 605
      "y": 62
      dimension: 31
    56:
      x: 564
      "y": 62
      dimension: 31
    57:
      x: 523
      "y": 62
      dimension: 31
    58:
      x: 482
      "y": 62
      dimension: 31
    59:
      x: 441
      "y": 62
      dimension: 31
    60:
      x: 400
      "y": 62
      dimension: 31
    61:
      x: 359
      "y": 62
      dimension: 31
    62:
      x: 318
      "y": 62
      dimension: 31
    63:
      x: 290
      "y": 162
      dimension: 32
    64:
      x: 290
      "y": 204
      dimension: 32
    65:
      x: 290
      "y": 246
      dimension: 32
    66:
      x: 290
      "y": 288
      dimension: 32
    67:
      x: 290
      "y": 330
      dimension: 32
    68:
      x: 290
      "y": 372
      dimension: 32
    69:
      x: 290
      "y": 414
      dimension: 32
    70:
      x: 290
      "y": 456
      dimension: 32
    71:
      x: 290
      "y": 498
      dimension: 32
    72:
      x: 290
      "y": 540
      dimension: 32
    73:
      x: 290
      "y": 582
      dimension: 32
    74:
      x: 290
      "y": 624
      dimension: 32
    75:
      x: 290
      "y": 666
      dimension: 32
    76:
      x: 290
      "y": 708
      dimension: 32
    77:
      x: 290
      "y": 750
      dimension: 32
    78:
      x: 290
      "y": 792
      dimension: 32
    79:
      x: 290
      "y": 834
      dimension: 32
    80:
      x: 290
      "y": 876
      dimension: 32
    81:
      x: 290
      "y": 918
      dimension: 37
    82:
      x: 336
      "y": 918
      dimension: 37
    83:
      x: 384
      "y": 918
      dimension: 37
    84:
      x: 431
      "y": 918
      dimension: 37
    85:
      x: 479
      "y": 918
      dimension: 37
    86:
      x: 526
      "y": 918
      dimension: 37
    87:
      x: 574
      "y": 918
      dimension: 37
    88:
      x: 621
      "y": 918
      dimension: 37
    89:
      x: 669
      "y": 918
      dimension: 37
    90:
      x: 716
      "y": 918
      dimension: 37
    91:
      x: 764
      "y": 918
      dimension: 37
    92:
      x: 811
      "y": 918
      dimension: 37
extendedLog: false
configVersion: "1.11.6"
